# conf/config.yaml
data:
  data_path: "./imagenet_subsets"
  classes:
    - "red_fox"
    - "red_wolf"
    - "strawberry"
  batch_size: 32

seed: 42

training:
  optimizer: "SGD"
  max_epoch: 3
  early_epoch: 1
  num_workers: 15


wandb:
  project_name: "MSc_MLAI"
  store_weight: "True"
  