# conf/config.yaml
data:
  data_path: "./imagenet_subsets"
  classes:
    - "red_fox"
    - "ox"
    - "doberman"
  batch_size: 32

training:
  optimizer: "Adam"  # or "SGD"
  max_epochs: 10

seed: 42

