# conf/config.yaml
data:
  data_path: "./imagenet_subsets"
  classes:
    - "red_fox"
    - "ox"
    - "doberman"
  batch_size: 32

training:
  optimizer: "Adam"  # or "SGD"
  max_epochs: 1

seed: 42

wandb:
  project_name: "MSc_MLAI"
  run_name: "Test Run"
  store_weight: "False"
  