# conf/config.yaml
data:
  data_path: "./imagenet_subsets"
  classes:
    - "red_fox"
    - "hyena"
    - "doberman"
  batch_size: 32

seed: 42

training:
  optimizer: "SGD"  # or "SGD"
  max_epoch: 2
  early_epoch: 1

wandb:
  project_name: "MSc_MLAI"
  run_name: "No Weight Run" #Deterministic Unique Name?
  store_weight: "True"
  